//TEST
### Get All Books
GET https://localhost:3000/books

### Get One Book
GET https://localhost:3000/books/67091ac8cab00070a1cc1cb0

### Create Book
POST https://localhost:3000/books HTTP/1.1
content-type: application/json
{
    "title": "test",
    "type": "test",
    "chapters": 1,
    "artist": "test",
    "author": "test",
    "firstAired": "test",
    "synopsis": "test"
}

### Update Book
PUT https://localhost:3000/books/67091ac8cab00070a1cc1cb0 HTTP/1.1
content-type: application/json
{
    "title": "The hero is back",
    "type": "Manhwa",
    "chapters": 94,
    "artist": "Ant Studio",
    "author": "Black Ajin",
    "firstAired": "03/03/2022",
    "synopsis": "The strongest hero of humanity, Kim Sung Bin.He threw everything on the line and fought... but he still couldn't prevent the destruction of the world.However, his legend has just begun as he returns 20 years into the past."
}

### Delete Book
DELETE https://localhost:3000/books/

### Get All Users
GET https://localhost:3000/users

### Create Book
POST https://localhost:3000/users HTTP/1.1
content-type: application/json
{
    "userName": "testName",
    "email": "test@gmail.com",
    "password": "test"
}


//PRODUCTION
### Get All Books
GET https://cse341-books-38m7.onrender.com/books

### Create Book
POST https://cse341-books-38m7.onrender.com/books HTTP/1.1
content-type: application/json
{
    "title": "test",
    "type": "test",
    "chapters": 1,
    "artist": "test",
    "author": "test",
    "firstAired": "test",
    "synopsis": "test"
}

### Get All Users
GET https://cse341-books-38m7.onrender.com/users

### Create User
POST https://cse341-books-38m7.onrender.com/users HTTP/1.1
content-type: application/json
{
    "userName": "testName",
    "email": "test@gmail.com",
    "password": "test"
}
